# Generated by Django 5.0.14 on 2026-07-14 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_creer_groupes_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offre', models.CharField(choices=[('essentiel', 'Essentiel'), ('standard', 'Standard'), ('diocese', 'Diocèse')], max_length=20, verbose_name='offre')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('annule', 'Annulé')], default='actif', max_length=20, verbose_name='statut')),
                ('date_debut', models.DateField(auto_now_add=True, verbose_name='date de début')),
                ('date_annulation', models.DateField(blank=True, null=True, verbose_name="date d'annulation")),
                ('paroisse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to='comptes.paroisse', verbose_name='paroisse')),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
            },
        ),
    ]
