# Generated by Django 5.0.14 on 2026-07-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='paroisse',
            name='est_active',
            field=models.BooleanField(default=True, help_text="Décoché : la paroisse est suspendue par la plateforme (distinct de l'abonnement, que le Curé gère lui-même). Personne ne peut plus s'y connecter tant qu'elle n'est pas réactivée.", verbose_name='active'),
        ),
    ]
