# Generated by Django 5.0.14 on 2026-07-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_paroisse_est_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='paroisse',
            name='avenue',
            field=models.CharField(blank=True, max_length=200, verbose_name='avenue'),
        ),
        migrations.AddField(
            model_name='paroisse',
            name='commune',
            field=models.CharField(blank=True, max_length=100, verbose_name='commune'),
        ),
        migrations.AddField(
            model_name='paroisse',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, verbose_name='quartier'),
        ),
        migrations.AlterField(
            model_name='paroisse',
            name='adresse',
            field=models.CharField(help_text="Composée automatiquement à l'inscription à partir de l'avenue, du quartier et de la commune ; modifiable librement ensuite.", max_length=255, verbose_name='adresse'),
        ),
    ]
