# Generated by Django 5.0.14 on 2026-07-17 16:55

from django.db import migrations, models


def renommer_offre_diocese_en_pro(apps, schema_editor):
    """L'offre « diocèse » entrait en collision avec Paroisse.diocese — un
    concept sans rapport (le diocèse de rattachement de la paroisse), pas
    un palier d'abonnement. Renomme les abonnements existants avant que le
    choix ne disparaisse des OFFRE_CHOICES."""
    Abonnement = apps.get_model("comptes", "Abonnement")
    Abonnement.objects.filter(offre="diocese").update(offre="pro")


def renommer_offre_pro_en_diocese(apps, schema_editor):
    Abonnement = apps.get_model("comptes", "Abonnement")
    Abonnement.objects.filter(offre="pro").update(offre="diocese")


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0008_paroisse_slug_etape3_unique'),
    ]

    operations = [
        migrations.RunPython(
            renommer_offre_diocese_en_pro, renommer_offre_pro_en_diocese
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='offre',
            field=models.CharField(choices=[('essentiel', 'Essentiel'), ('standard', 'Standard'), ('pro', 'Pro')], max_length=20, verbose_name='offre'),
        ),
    ]
