# Generated by Django 5.0.14 on 2026-07-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenuVitrine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_hero', models.CharField(default="Le registre de votre paroisse, tenu avec la même rigueur qu'un missel relié", max_length=200, verbose_name='titre principal')),
                ('accroche_hero', models.TextField(default='ParoisseConnect rassemble paroissiens, sacrements, célébrations et dons dans un seul registre numérique, pensé pour un secrétariat paroissial — pas pour un tableau de bord marketing.', verbose_name='accroche')),
                ('image_hero', models.ImageField(blank=True, null=True, upload_to='vitrine/', verbose_name='image')),
                ('titre_cta', models.CharField(default='Prêt pour votre paroisse ?', max_length=200, verbose_name="titre de l'appel à l'action")),
                ('texte_cta', models.CharField(default='Créez votre espace ParoisseConnect en quelques minutes, sans engagement.', max_length=300, verbose_name="texte de l'appel à l'action")),
            ],
            options={
                'verbose_name': 'contenu de la vitrine',
                'verbose_name_plural': 'contenu de la vitrine',
            },
        ),
    ]
