# Generated by Django 5.0.14 on 2026-07-14 15:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0002_creer_groupes_roles'),
        ('paroissiens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('date', models.DateField(verbose_name='date')),
                ('type_don', models.CharField(choices=[('dime', 'Dîme'), ('offrande', 'Offrande'), ('quete', 'Quête'), ('autre', 'Autre')], max_length=20, verbose_name='type')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile money'), ('virement', 'Virement'), ('cheque', 'Chèque')], max_length=20, verbose_name='mode de paiement')),
                ('paroisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dons', to='comptes.paroisse', verbose_name='paroisse')),
                ('paroissien', models.ForeignKey(blank=True, help_text='Laisser vide pour un don anonyme.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dons', to='paroissiens.paroissien', verbose_name='donateur')),
            ],
            options={
                'verbose_name': 'don',
                'verbose_name_plural': 'dons',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RecuFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, editable=False, max_length=30, verbose_name='numéro')),
                ('date_emission', models.DateField(default=django.utils.timezone.now, verbose_name="date d'émission")),
                ('don', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recu_fiscal', to='finances.don', verbose_name='don')),
            ],
            options={
                'verbose_name': 'reçu fiscal',
                'verbose_name_plural': 'reçus fiscaux',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.AddConstraint(
            model_name='recufiscal',
            constraint=models.UniqueConstraint(fields=('don',), name='unique_recu_fiscal_par_don'),
        ),
    ]
