# Generated by Django 5.0.14 on 2026-07-23 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0009_alter_abonnement_offre'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, verbose_name='libellé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('date', models.DateField(verbose_name='date')),
                ('categorie', models.CharField(choices=[('charges', 'Charges (eau, électricité, loyer)'), ('entretien', 'Entretien et travaux'), ('liturgie', 'Liturgie et culte'), ('salaires', 'Salaires et indemnités'), ('charite', 'Charité et aumônes'), ('administration', 'Administration'), ('autre', 'Autre')], max_length=20, verbose_name='catégorie')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile money'), ('virement', 'Virement'), ('cheque', 'Chèque')], max_length=20, verbose_name='mode de paiement')),
                ('beneficiaire', models.CharField(blank=True, help_text='Fournisseur ou personne réglée (facultatif).', max_length=150, verbose_name='bénéficiaire')),
                ('paroisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='comptes.paroisse', verbose_name='paroisse')),
            ],
            options={
                'verbose_name': 'dépense',
                'verbose_name_plural': 'dépenses',
                'ordering': ['-date'],
            },
        ),
    ]
