# Generated by Django 5.0.14 on 2026-07-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_depense'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='devise',
            field=models.CharField(choices=[('CDF', 'Franc congolais (FC)'), ('USD', 'Dollar (USD)')], default='CDF', max_length=3, verbose_name='devise'),
        ),
        migrations.AddField(
            model_name='don',
            name='devise',
            field=models.CharField(choices=[('CDF', 'Franc congolais (FC)'), ('USD', 'Dollar (USD)')], default='CDF', max_length=3, verbose_name='devise'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant'),
        ),
        migrations.AlterField(
            model_name='don',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant'),
        ),
    ]
