# Generated by Django 5.0.14 on 2026-07-23 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0009_alter_abonnement_offre'),
        ('finances', '0003_depense_devise_don_devise_alter_depense_montant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffrandeMesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, help_text='Ex. « Quête messe dominicale ». Facultatif.', max_length=150, verbose_name='libellé')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant')),
                ('devise', models.CharField(choices=[('CDF', 'Franc congolais (FC)'), ('USD', 'Dollar (USD)')], default='CDF', max_length=3, verbose_name='devise')),
                ('date', models.DateField(verbose_name='date')),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('mobile_money', 'Mobile money'), ('virement', 'Virement'), ('cheque', 'Chèque')], default='especes', max_length=20, verbose_name='mode de paiement')),
                ('paroisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offrandes_messe', to='comptes.paroisse', verbose_name='paroisse')),
            ],
            options={
                'verbose_name': 'offrande de messe',
                'verbose_name_plural': 'offrandes de messe',
                'ordering': ['-date'],
            },
        ),
    ]
