# Generated by Django 5.0.14 on 2026-07-14 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0002_creer_groupes_roles'),
        ('paroissiens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bapteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acte', models.CharField(blank=True, editable=False, max_length=30, verbose_name="numéro d'acte")),
                ('date', models.DateField(verbose_name='date')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='lieu')),
                ('celebrant', models.CharField(max_length=200, verbose_name='célébrant')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="date d'enregistrement")),
                ('parrain', models.CharField(blank=True, max_length=200, verbose_name='parrain')),
                ('marraine', models.CharField(blank=True, max_length=200, verbose_name='marraine')),
                ('paroisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptes.paroisse', verbose_name='paroisse')),
                ('paroissien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paroissiens.paroissien', verbose_name='paroissien')),
            ],
            options={
                'verbose_name': 'baptême',
                'verbose_name_plural': 'baptêmes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Communion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acte', models.CharField(blank=True, editable=False, max_length=30, verbose_name="numéro d'acte")),
                ('date', models.DateField(verbose_name='date')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='lieu')),
                ('celebrant', models.CharField(max_length=200, verbose_name='célébrant')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="date d'enregistrement")),
                ('paroisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptes.paroisse', verbose_name='paroisse')),
                ('paroissien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paroissiens.paroissien', verbose_name='paroissien')),
            ],
            options={
                'verbose_name': 'communion',
                'verbose_name_plural': 'communions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acte', models.CharField(blank=True, editable=False, max_length=30, verbose_name="numéro d'acte")),
                ('date', models.DateField(verbose_name='date')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='lieu')),
                ('celebrant', models.CharField(max_length=200, verbose_name='célébrant')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="date d'enregistrement")),
                ('paroisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptes.paroisse', verbose_name='paroisse')),
                ('paroissien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paroissiens.paroissien', verbose_name='paroissien')),
            ],
            options={
                'verbose_name': 'confirmation',
                'verbose_name_plural': 'confirmations',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Funerailles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acte', models.CharField(blank=True, editable=False, max_length=30, verbose_name="numéro d'acte")),
                ('date', models.DateField(verbose_name='date')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='lieu')),
                ('celebrant', models.CharField(max_length=200, verbose_name='célébrant')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="date d'enregistrement")),
                ('paroisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptes.paroisse', verbose_name='paroisse')),
                ('paroissien', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paroissiens.paroissien', verbose_name='paroissien')),
            ],
            options={
                'verbose_name': 'funérailles',
                'verbose_name_plural': 'funérailles',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Mariage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acte', models.CharField(blank=True, editable=False, max_length=30, verbose_name="numéro d'acte")),
                ('date', models.DateField(verbose_name='date')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='lieu')),
                ('celebrant', models.CharField(max_length=200, verbose_name='célébrant')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="date d'enregistrement")),
                ('temoins', models.CharField(blank=True, max_length=300, verbose_name='témoins')),
                ('conjoint1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mariages_conjoint1', to='paroissiens.paroissien', verbose_name='premier conjoint')),
                ('conjoint2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mariages_conjoint2', to='paroissiens.paroissien', verbose_name='second conjoint')),
                ('paroisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptes.paroisse', verbose_name='paroisse')),
            ],
            options={
                'verbose_name': 'mariage',
                'verbose_name_plural': 'mariages',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MentionMarginale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mention', models.CharField(choices=[('mariage', 'Mariage'), ('ordination', 'Ordination'), ('deces', 'Décès'), ('autre', 'Autre')], max_length=20, verbose_name='type')),
                ('date', models.DateField(verbose_name='date')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='référence')),
                ('bapteme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_marginales', to='sacrements.bapteme', verbose_name='baptême')),
                ('paroisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptes.paroisse', verbose_name='paroisse')),
            ],
            options={
                'verbose_name': 'mention marginale',
                'verbose_name_plural': 'mentions marginales',
                'ordering': ['date'],
            },
        ),
        migrations.AddConstraint(
            model_name='bapteme',
            constraint=models.UniqueConstraint(fields=('paroisse', 'numero_acte'), name='unique_numero_acte_bapteme'),
        ),
        migrations.AddConstraint(
            model_name='communion',
            constraint=models.UniqueConstraint(fields=('paroisse', 'numero_acte'), name='unique_numero_acte_communion'),
        ),
        migrations.AddConstraint(
            model_name='confirmation',
            constraint=models.UniqueConstraint(fields=('paroisse', 'numero_acte'), name='unique_numero_acte_confirmation'),
        ),
        migrations.AddConstraint(
            model_name='funerailles',
            constraint=models.UniqueConstraint(fields=('paroisse', 'numero_acte'), name='unique_numero_acte_funerailles'),
        ),
        migrations.AddConstraint(
            model_name='mariage',
            constraint=models.UniqueConstraint(fields=('paroisse', 'numero_acte'), name='unique_numero_acte_mariage'),
        ),
    ]
