# Generated by Django 5.0.14 on 2026-07-14 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('comptes', '0002_creer_groupes_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('date_publication', models.DateField(verbose_name='date de publication')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annonces', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('groupe_cible', models.ForeignKey(blank=True, help_text='Laisser vide pour une annonce visible de toute la paroisse.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='groupe cible')),
                ('paroisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annonces', to='comptes.paroisse', verbose_name='paroisse')),
            ],
            options={
                'verbose_name': 'annonce',
                'verbose_name_plural': 'annonces',
                'ordering': ['-date_publication'],
            },
        ),
    ]
