# Generated by Django 5.0.14 on 2026-07-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='publique',
            field=models.BooleanField(default=False, help_text='Affichée sur la page publique de la paroisse, consultable sans compte.', verbose_name='visible publiquement'),
        ),
    ]
