# Generated by Django 5.0.14 on 2026-07-14 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0002_creer_groupes_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='nom de famille')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('paroisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='familles', to='comptes.paroisse', verbose_name='paroisse')),
            ],
            options={
                'verbose_name': 'famille',
                'verbose_name_plural': 'familles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Paroissien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='sexe')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='date de naissance')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='paroissiens/', verbose_name='photo')),
                ('famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='paroissiens.famille', verbose_name='famille')),
                ('paroisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paroissiens', to='comptes.paroisse', verbose_name='paroisse')),
            ],
            options={
                'verbose_name': 'paroissien',
                'verbose_name_plural': 'paroissiens',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
