# Generated by Django 5.0.14 on 2026-07-14 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comptes', '0002_creer_groupes_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Celebration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('heure', models.TimeField(verbose_name='heure')),
                ('type_celebration', models.CharField(choices=[('messe', 'Messe'), ('vigile', 'Vigile'), ('fete', 'Fête'), ('autre', 'Autre')], max_length=20, verbose_name='type')),
                ('celebrant', models.CharField(max_length=200, verbose_name='célébrant')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='lieu')),
                ('paroisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='celebrations', to='comptes.paroisse', verbose_name='paroisse')),
            ],
            options={
                'verbose_name': 'célébration',
                'verbose_name_plural': 'célébrations',
                'ordering': ['date', 'heure'],
            },
        ),
        migrations.CreateModel(
            name='IntentionMesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demandeur', models.CharField(max_length=200, verbose_name='demandeur')),
                ('intention', models.CharField(max_length=300, verbose_name='intention')),
                ('montant_offrande', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="montant de l'offrande")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('celebree', 'Célébrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20, verbose_name='statut')),
                ('celebration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentions', to='celebrations.celebration', verbose_name='célébration')),
                ('paroisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptes.paroisse', verbose_name='paroisse')),
            ],
            options={
                'verbose_name': 'intention de messe',
                'verbose_name_plural': 'intentions de messe',
                'ordering': ['-celebration__date'],
            },
        ),
    ]
