# Generated by Django 5.0.14 on 2026-07-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentionmesse',
            name='devise',
            field=models.CharField(choices=[('CDF', 'Franc congolais (FC)'), ('USD', 'Dollar (USD)')], default='CDF', max_length=3, verbose_name='devise'),
        ),
        migrations.AlterField(
            model_name='intentionmesse',
            name='montant_offrande',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="montant de l'offrande"),
        ),
    ]
